# Use root/example as user/password credentials
# docker-compose up
version: '3.1'

services:
    db:
      image: mariadb
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: db_data_123
      ports:
        - 3307:3306

    php72_apache:
      build:
        context: ./.docker
      volumes:
        - .apache/:/etc/apache2/v-host/
        - .:/var/www
      ports:
        - 8030:80
